config/routes.rb
Rails.application.routes.draw do
  #resources :orders
  get "/", to: "orders#new"
  post "/create", to: "orders#create"
  get "/orders", to: "orders#index"
  get "/orders/:id", to: "orders#show"
  #get '/dishes/[:id]', to: 'dishes#show'
  resources :dishes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :order_dishes
  has_many :orders, through: :order_dishes
  has_and_belongs_to_many :ingredients

  def get_string_ingredients
    self.ingredients.map{|i| i.name}.join(", ")
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :dishes
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_dishes
  has_many :dishes, through: :order_dishes
end

app/models/order_dish.rb
class OrderDish < ApplicationRecord
  belongs_to :order
  belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show  ]

  def show
  end

  private
    def set_dish
      @dish = Dish.find(params[:id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :get_all_dishes, only: %i[ new ]
  before_action :get_all_ingredients, only: %i[ new ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if params[:commit] == "Search"
      @dishes = Ingredient.where(name: params.select {|k,v| v=="1"}.keys).map {|i| p i.dishes}.inject(:&)
      @dishes = [] if @dishes.nil?
    end
    @order = Order.new
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new
    ActiveRecord::Base.transaction do
      raise ActiveRecord::TransactionIsolationError if dishes_counts_from_params.blank?
      respond_to do |format|
        if @order.save
          dishes_counts_from_params.each do |dish_id, count|
            OrderDish.create!(order_id: @order.id, dish_id: dish_id.to_i, count: count)
          end
          format.html { redirect_to "/", notice: "Order was successfully created." }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    end
  rescue ActiveRecord::TransactionIsolationError => e
    format.html { redirect_to new_order_path, status: :unprocessable_entity }
    format.json { render json: e, status: :unprocessable_entity }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.fetch(:order, {})
    end

    def get_all_dishes
      @dishes = Dish.all
    end

    def get_all_ingredients
      @ingredients = Ingredient.all
    end

  def dishes_counts_from_params
    params.require(:dishes).to_unsafe_h.select {|k,v| v.to_i>0}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/dishes/show.html.erb
<section id="hero" class="d-flex align-items-center justify-content-center">


  <div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-8">
        <h1><%= @dish.name %></h1>
        <h2>Заказывайте вкусную еду только у нас</h2>
      </div>
    </div>
    <div class="row mt-5 justify-content-center">
        <div class="col-xl-2 col-md-4 d-flex align-items-stretch">
          <div class="w-100 p-3">
            <div class="icon-box">
              <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="#ffc451" class="bi bi-bag-check" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
              </svg>
              <h3><a href='/'  title=<%= @dish.get_string_ingredients %> ><%= @dish.name %></a></h3>

            </div>
          </div>
        </div>
    </div>
  </div>
</section>

<section class="about my-5" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 order-1 order-lg-2">
        <img class="img-fluid" src="https://img3.goodfon.ru/wallpaper/nbig/1/b8/doski-eda-yagody.jpg">
      </div>
      <div class="col-lg-5 pt-lg-0 order-2 order-lg-1 content">
        <h3>Ингредиенты</h3>
        <p class="fst-italic">
          В данное блюдо входит:
        </p>
          <ul>
            <% @dish.ingredients.each do |ingredient| %>
              <li>
                <div class="form-check form-switch">
                  <%= ingredient.name %>
                </div>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderingDishes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", media: 'all' %>
    <%= stylesheet_link_tag "main", media: 'all' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>

  <header id="header" class="fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000;">
      <div class="container">
        <a href="/" class="navbar-brand">Ordering</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navContent"
                aria-controls="navContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navContent">
          <ul class="navbar-nav mr-auto mb-3 mb-lg-0">
            <li class="nav-item">
              <a href="/orders" class="nav-link">Все заказы</a>
            </li>
            <li class="nav-item">
              <a href="/" class="nav-link">Сделать заказ</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <%= yield %>

  <section class="cta mb-5">
    <div class="container text-center">
      <h3>Обратная связь</h3>
      <p>
        Переходите для общения со мной в телеграмм
      </p>
      <a href="https://t.me/MechaelDodo" target="_blank" class="cta-btn">Telegram</a>
    </div>
  </section>





  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with url: "/create", method: :post do |form| %>
<section id="hero" class="d-flex align-items-center justify-content-center">
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-8">
        <h1>Ordering</h1>
        <h2>Заказывайте вкусную еду только у нас</h2>
        <div>
          <%= form.submit class:"crt-btn", value:"Заказать" %>
        </div>
      </div>
    </div>
    <div class="row mt-5 justify-content-center">
      <div class="carousel slide" data-ride="carousel" id="blogCarousel">
        <ol class="carousel-indicators">
          <% unless @dishes.blank? %>
            <li data-bs-target="#blogCarousel" data-bs-slide-to="0" class="active"></li>
            <% if @dishes.count > 4 and @dishes.count/4.0 > @dishes.count/4 %>
              <% (1..(@dishes.count/4)).each do |i| %>
              <li data-bs-target="#blogCarousel" data-bs-slide-to=<%= i %>>></li>
              <% end %>
            <% elsif  @dishes.count > 4 and @dishes.count/4.0 > @dishes.count/4 %>
              <% (1..(@dishes.count/4-1)).each do |i| %>
                <li data-bs-target="#blogCarousel" data-bs-slide-to=<%= i %>>></li>
              <% end %>
            <% end %>
          <% end %>
        </ol>
        <div class="container carousel-inner">
          <% unless @dishes.blank? %>
          <div class="carousel-item active">
            <div class="row">
              <% @dishes[0...4].each do |dish| %>
              <div class="col-md-3">
                <div class="col-xl-2 col-md-4 d-flex align-items-stretch">
                  <div class="w-100 p-3">
                    <div class="icon-box">
                      <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="#ffc451" class="bi bi-bag-check" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                        <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                      </svg>
                      <h3 class="h-title" data-tooltip=<%= dish.get_string_ingredients %> ><a href=<%= dish_path(dish) %>><%= dish.name %></a></h3>

                      <div class="counter">
                        <button class="counter__btn btn btn-dark" name="button" type="button" data-direction="plus"><i class="bi bi-caret-up-fill"></i></button>
                        <%= form.text_area "dishes[#{ dish.id }]", class:"counter__value", value: "0", required: true, readonly:true%>
                        <button class="counter__btn btn btn-dark" name="button" type="button" data-direction="minus"><i class="bi bi-caret-down-fill"></i></button>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
              <% i = 5 %>
              <% while i< @dishes.count %>
          <div class="carousel-item">
            <div class="row">
              <% @dishes[i...i+4].each do |dish| %>
                  <div class="col-md-3">
                    <div class="col-xl-2 col-md-4 d-flex align-items-stretch">
                      <div class="w-100 p-3">
                        <div class="icon-box">
                          <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="#ffc451" class="bi bi-bag-check" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                            <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                          </svg>
                          <h3 class="h-title" data-tooltip=<%= dish.get_string_ingredients %> ><a href=<%= dish_path(dish) %>><%= dish.name %></a></h3>
                          <div class="counter">
                            <button class="counter__btn btn btn-dark" name="button" type="button" data-direction="plus"><i class="bi bi-caret-up-fill"></i></button>
                            <%= form.text_area "dishes[#{ dish.id }]", class:"counter__value", value: "0", required: true, readonly:true%>
                            <button class="counter__btn btn btn-dark" name="button" type="button" data-direction="minus"><i class="bi bi-caret-down-fill"></i></button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% i+=4 %>
            </div>
          </div>
            <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>
<section class="about my-5" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 order-1 order-lg-2" style="margin-top: 20px;">
        <img class="img-fluid" src="https://i.artfile.ru/3300x2248_871244_[www.ArtFile.ru].jpg">
      </div>
      <div class="col-lg-5 pt-lg-0 order-2 order-lg-1 content">
        <br>
        <h3>Заказы:</h3>
        <ul>
          <% @orders.each do |order| %>
            <li>
              <div class="form-check form-switch">
                <a class="btn btn-dark" href=<%="/orders/#{order.id}.json"%>  target="_blank" class="cta-btn">
                  Заказ #<%=order.id %>
                </a>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/orders/new.html.erb
<%= render "form", order: @order %>

  <section class="about my-5" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 order-1 order-lg-2">
          <img class="img-fluid" src="https://img3.goodfon.ru/wallpaper/nbig/1/b8/doski-eda-yagody.jpg">
        </div>
        <div class="col-lg-5 pt-lg-0 order-2 order-lg-1 content">
          <h3>Ингредиенты</h3>
          <p class="fst-italic">
            Поиск блюд с нужными вам ингриденетами
          </p>
          <%= form_with url: "/", method: :get do |form| %>
          <ul>
            <% @ingredients.each do |ingredient| %>
            <li>
              <div class="form-check form-switch">
                <%= form.check_box "#{ingredient.name}", class:"form-check-input"  %>
                <%= ingredient.name %>
              </div>
            </li>
            <% end %>
          </ul>
            <button type="submit" name="commit" value="Search" class="btn btn-dark" data-disable-with="Search"><i class="bi bi-search"></i></button>
            <%= form.submit "Показать все", class:"btn btn-dark" %>
          <% end %>
        </div>
      </div>
    </div>
  </section>

<script>
    const counter = function () {
        const btns = document.querySelectorAll('.counter__btn');
        btns.forEach(btn => {
            btn.addEventListener('click', function () {
                const direction = this.dataset.direction;
                const inp = this.parentElement.querySelector('.counter__value');
                const currentValue = +inp.value;
                let newValue;
                if (direction === 'plus') {
                    newValue = currentValue + 1;
                } else {
                    newValue = currentValue - 1 > 0 ? currentValue - 1 : 0;
                }
                inp.value = newValue;
            })
        })

    }

    counter();
</script>